runtime: php81

handlers:
- url: /(.*\.(css|js|gif|png|jpg|svg|woff|woff2|ttf))$
  static_files: \1
  upload: .*\.(css|js|gif|png|jpg|svg|woff|woff2|ttf)$

#serve your app
- url: .*
  script:auto




