# creame la configuracion de la app para subrilo a app engine cgp
# https://cloud.google.com/appengine/docs/standard/python3/config/appref

runtime: python37
entrypoint: gunicorn -b :$PORT main:app

# https://cloud.google.com/appengine/docs/standard/python3/config/appref#handlers_element
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
```   

## 3. Crear el archivo main.py
```python
# Path: main.py
# creame la configuracion de la app para subrilo a app engine cgp
# https://cloud.google.com/appengine/docs/standard/python3/config/appref




